### ISSUE TITLE
Error when changing police outfit

### ISSUE THREAD

**Issue by kaykayy** [esx-framework/esx_service#22]
SCRIPT ERROR: @esx_service/server/main.lua:10: bad argument #1 to 'pairs' (table expected, got nil)
> GetInServiceCount (@esx_service/server/main.lua:10)
> ref (@esx_service/server/main.lua:39)
> TriggerServerCallback (@es_extended/server/functions.lua:160)
> handler (@es_extended/server/common.lua:71)
`

**Comment by Falyandar** [comment]
im having the same issue

**Comment by Falyandar** [comment]
ok never mind i fixed it

**Comment by SetaWinsU** [comment]
> ok never mind i fixed it

Can you tell me how did you fixed it?

**Comment by tr1age** [comment]
would love to know the fix too.

**Comment by JJPivot** [comment]
> ok never mind i fixed it

I am having the issue, does anyone have a fix for this?

**Comment by Raydiaa** [comment]
Funny.. you ask for help and cant share the fix with the people who need to fix it as well.

**Comment by Raydiaa** [comment]
> > ok never mind i fixed it
> 
> I am having the issue, does anyone have a fix for this?



> would love to know the fix too.



> > ok never mind i fixed it
> 
> Can you tell me how did you fixed it?


Hello! On the config.lua of the esx_policejob change de number of people on service to a high number, like 40 for example, instead of -1 :) make sure esx_service and esx_policejob are updated and it should work fine! Let me know if it doesnt fix it.

**Comment by MAC-gg** [comment]
Worked for me! Thanks!

I checked this issue earlier today and raged at the fact that the commenter didn't post the solution. Thanks for posting yours.

**Comment by Raydiaa** [comment]
> Worked for me! Thanks!
> 
> I checked this issue earlier today and raged at the fact that the commenter didn't post the solution. Thanks for posting yours.

No worries 🥇
