### ISSUE TITLE
esx_policejob - Vehicle Shop Bug (authorizedVehicles)

### ISSUE THREAD

**Issue by CoreBitX** [esx-framework/esx_service#6]
Hello Guys
I can't buy a vehicle. They keep saying I don't have permission to have a garage and I have a police job with level 4

**Comment by Gellipapa** [comment]
@CoreBitX Hi! Here you have to specify which vehicle you have access to the grade, you probably either don't have a car or you are not in that grade. https://github.com/esx-framework/esx_policejob/blob/4904fa62102894b604ea8308f4accd0207772b9a/config.lua#L133
